### DISCUSSION TITLE
almost all primitive types are Send, aside from raw pointers & Rc<T>

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#390] [Joy of Programming]
```yaml
- Interestingly, the Rust language has very FEW concurrency features
- Two concurrency concepts are embedded in the language: the std::marker traits Sync and Send.
- Send marker trait:
  - **OWNERSHIP** of values of the type implementing Send can be transferred between threads
```
```yaml
- Almost every Rust type is Send, but there are some exceptions, including Rc<T>
- Rc<T> cannot be Send because if you cloned and tried to transfer **OWNERSHIP** of the clone to another thread:
  - Both threads might update the reference count at the same time
- For this reason, Rc<T> is implemented for use in single-threaded situations 
- Above is good since you don’t want to pay the thread-safe performance penalty
```
```yaml
- Any type composed entirely of Send types is automatically marked as Send as well
- Almost all primitive types are Send
```
