### DISCUSSION TITLE
build go app using github actions on mac, windows, linux

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#410] [Joy of Programming]
```
https://github.com/edsrzf/mmap-go/blob/main/.github/workflows/build-test.yml
```

```yaml
name: Build and Test
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '~1.17.0'
    - name: Build
      run: go build .
    - name: Test
      run: go test ./...
```
