### DISCUSSION TITLE
multiple DNS records pointing to single public Load Balancer IP address

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#416] [Joy of Programming]
```
https://platform9.com/blog/ultimate-guide-to-kubernetes-ingress-controllers/
```

```yaml
- Different ingress resource per host
- Which allows us to control traffic with multiple hostnames
- While using the same external IP for A Record creation
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: hello-world-prod
annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules: # traffic comes via the same LB IP & gets routed based on host name & path
  - host: test.example.com
   http:
     paths:
     - path: /hello-world
       pathType: Prefix
       backend:
         service:
           name: hello-world-test
           port:
             number: 8080
  - host: prod.example.com
    http:
      paths:
      - path: /hello-world
        pathType: Prefix
        backend:
          service:
            name: hello-world-prod
            port:
              number: 8080
```
