### DISCUSSION TITLE
kubernetes ingress to terminate SSL / TTL

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#417] [Joy of Programming]
```
https://platform9.com/blog/ultimate-guide-to-kubernetes-ingress-controllers/
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: hello-world
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true" # redirect HTTP traffic to HTTPS
   cert-manager.io/cluster-issuer: letsencrypt-prod # select issuer to use for certificate
spec:
  ingressClassName: nginx
  tls:
  - hosts: # host we want to route traffic for, a subdomain of example.com called test
    - test.example.com
    secretName: test-example-tls # secret to store the certificate information; auto configured
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /hello-world
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 8080
```
