### DISCUSSION TITLE
traffic split for micro services with different scaling needs

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#418] [Joy of Programming]
```
https://platform9.com/blog/ultimate-guide-to-kubernetes-ingress-controllers/
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-and-universe
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target:
spec:
  ingressClassName: nginx
  rules:
  - host: test.example.com
    http:
      paths: # split traffic to different service endpoints & deployments based on path
      - path: /hello-world # a deployment & service
        pathType: Prefix
        backend:
          service:
            name: hello-world # can be scaled up independent of hello-universe
            port:
              number: 8080
      - path: /hello-universe # another deployment & service
        pathType: Prefix
        backend:
          service:
            name: hello-universe # can be scaled up independent of hello-world
            port:
              number: 8080
```
