### DISCUSSION TITLE
the need for ingress in kubernetes

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#419] [Joy of Programming]
```
https://platform9.com/blog/ultimate-guide-to-kubernetes-ingress-controllers/
```

```yaml
- Kubernetes uses **IP proxy** techniques to ensure that traffic intended for a Service
- Is routed to one of the concerned Pod container instances
- Since this uses a **virtual IP address** internal to the cluster
- External services need a different way to access the Service endpoint
- Ingress solve the above problem
```

```yaml
- To overcome these NodePort limitations
- Kubernetes provides an option to rely on a cloud provider’s Load Balancer service
- A load balancer allows us to use a single IP address and more familiar ports
- Instead of keeping a list of the nodes & the port associated with the NodePort
- We can use the IP of the load balancer
```

```yaml
- Ingress Resources are used to update the configuration within the Ingress Controller
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # exact ingress controller when multiple ingress controllers exist
  rules: # basic layer 7 feature
  - host: test.example.com # single DNS entry for a host
    http:
      paths: # path based load balancing
      - path: /hello-world
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 8080
```
