### DISCUSSION TITLE
arp cache - neighbor table overflow

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#423] [Joy of Programming]
```
https://openai.com/blog/scaling-kubernetes-to-2500-nodes/
```

```yaml
- Despite our DNS tuning, we still saw intermittent issues with DNS resolution
- An engineer reported that nc -v to their Redis server was taking over 30 seconds 
- Investigation of the Redis pod’s host showed something wrong with the network:
  - Communication on any port was hanging for multiple seconds
  - And no DNS names could be resolved via the local dnsmasq daemon
  - With dig just printing a cryptic failure message: 
    - socket.c:1915: internal_send: 127.0.0.1#53: Invalid argument
- The dmesg log was more informative: neighbor table overflow! 
  - Which meant that the ARP cache had run out of space
- ARP maps a network address such as an IPv4 address, to a physical address, such as a MAC address
```

#### fix by setting a few options in /etc/sysctl.conf
```sh
net.ipv4.neigh.default.gc_thresh1 = 80000
net.ipv4.neigh.default.gc_thresh2 = 90000
net.ipv4.neigh.default.gc_thresh3 = 100000
```

```yaml
- It’s common to tune this setting in HPC clusters
- And is particularly relevant in Kubernetes clusters since every pod has its own IP address 
- Which consumes space in the ARP cache
```
