### DISCUSSION TITLE
ipvs vs iptables - modes in kube-proxy

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#428] [Joy of Programming]
```
https://www.tigera.io/blog/comparing-kube-proxy-modes-iptables-or-ipvs/
```

```yaml
- IPVS is O(1)
- iptables is O(N)
```

#### performance of kube-proxy in the context of your microservices
```yaml
- Impact on round-trip response times:
  - When one microservice makes an API call to another microservice
  - Average time for the first microservice to send the request to
  - & receive the response back from the second microservice
- Impact on total CPU usage:
  - What is the total CPU usage of a host
  - When running your microservices
  - Including userspace and kernel/system usage
  - Across all the processes that are needed to support the microservices including kube-proxy
```

```yaml
- To illustrate this we ran a “client” microservice pod on a dedicated node
- Generating 1,000 requests per second to a Kubernetes service
- The K8s service was backed by 10 pods running on other nodes in the cluster
- We then measured performance on the client node in both iptables and IPVS mode
- With various numbers of Kubernetes services with each service being backed by 10 pods
- Up to a maximum of 10,000 services (with 100,000 service backends)
- We used a simple test tool written in golang as our client microservice
- And used standard NGINX for the backend pods of the server microservice
```

#### most microservices will use persistent or “keepalive” connections
```yaml
- i.e. each connection is reused across multiple requests
- Rather than requiring a new connection per request
- Most new connections require a three-way TCP-handshake across the network:
  - Which takes time & CPU
```

#### testing
```yaml
- To illustrate these differences we tested with and without keepalive connections
- For the keepalive connections, we used NGINX’s default configuration
- Which keeps each connection alive for re-use for up to 100 requests
```

```yaml
- Linux uses connection tracking (conntrack)
- That is able to match packets against existing connections very efficiently
- If a packet is matched in conntrack
- Then it doesn’t need to go through kube-proxy’s iptables or IPVS rules
```

#### conclusion
```yaml
- At scales significantly beyond 1,000 services
- kube-proxy’s IPVS mode can offer some nice performance improvements
- As a general guide, for microservices that use persistent “keepalive” connections
- Running on a modern kernel, the benefits will likely be relatively modest
```

```yaml
- Microservices that DON'T use persistent connections, or when running on older kernels
- Then switching to kube-proxy to IPVS mode will likely be a good win
```

```yaml
- Independent of performance considerations, you should also consider using IPVS mode
- If you have a need for more sophisticated load balancing scheduling algorithms 
- kube-proxy’s iptables is based on random load balancing
```

```yaml
- If you aren’t sure whether IPVS will be a win for you then stick with kube-proxy
- It’s had a ton more in-production hardening
```
