### DISCUSSION TITLE
goodbye docker compose - welcome kubelet

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#453] [Joy of Programming]
```
https://bmiguel-teixeira.medium.com/goodbye-docker-compose-hello-kubelet-75306472de27
```

##### Install via Apt & Debian Registry
```
- Install the public key.
- sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
```

```
- Install the repo url & config
- echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
```

```
- Install the Agent
- apt update
- apt install -y kubelet=1.23*
```

```
- Configure the Agent
- Now that Kubelet is available in your system we have a couple of ways of setting it up
- The Kubelet binary supports cli arguments for pretty much everything
- However, most cli arguments are deprecated in favor of leveraring a configuration file.
- Use the following example as the bare bones configuration for bootstrapping a standalone Kubelet.
```

```yaml
# /etc/kubernetes/kubelet.yaml
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
failSwapOn: false # by default, Kubelet exits if SWAP is enabled
syncFrequency: 5s # reconciliation time
staticPodPath: /etc/kubernetes/manifests # folder to look for files
```

```
- If you installed it via a package manager like apt or yum
- it most likely setup a systemd unit file
```

```
- See status of it: systemctl status kubelet.service
- Edit the systemd unit file (vi /lib/systemd/system/kubelet.service) 
- to leverage the configuration file you created previously 
- add the --config /etc/kubernetes/kubelet.yaml to the ExecStart section as shown below
- Reload and Restart
- systemctl daemon-reload
- systemctl restart kubelet.service
```

```yaml
# Running Containers — The Kubernetes Way
# Let’s start small and run a simple nginx container.
# /etc/kubernetes/manifests/nginx.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```

```
- docker ps
- And you can see that Kubelet automatically detects the file and creates the required container, 
- including the k8s.gcr.io/pause:3.6 container to create a POD
```

```yaml
# An example
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: content
    image: busybox
    command:
    - sh
    - -c
    - "echo hello world > /usr/share/nginx/html/index.html"
    volumeMounts:
    - name: content-vol
      mountPath: /usr/share/nginx/html
  containers:
  - name: web
    image: nginx
    ports:
    - name: web
      containerPort: 80
      hostPort: 8080
    livenessProbe:
      httpGet:
        port: 80
        path: /
    resources:
      requests:
       cpu: 100m
    volumeMounts:
    - name: content-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: content-vol
    emptyDir: {}
```

```
docker ps -a --format "table {{.Image}}\t{{.Status}}\t{{.Command}}"
```

```yaml
- We can see 3 containers:
- pause container is running
- nginx container is running
- busybox initContainer is exited after running successfully
- And doing a quick curl against the Nginx webserver, we can see its output hello world, as expected
```

```yaml
- Some Useful Commands
- See Kubelet logs: journalctl -fu kubelet.service
- See Kubelet Status: systemctl status kubelet.service
- Restart Kubelet Service: systemctl restart kubelet.service
- Reload Systemd changes: systemctl daemon-reload
```
