### DISCUSSION TITLE
prometheus rule generation

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#466] [Joy of Programming]
```yaml
apiVersion: v1
data:
  config.yaml: |
    drop_regex:
      - '^(up|job:)'

    rules_template: |
      {{ range $metric := .MetricNames }}
      - name: {{$metric}}
        rules:
        {{- if eq (match $metric `(?:_total|_count|_bucket)$`) true }}
        # Counter or histogram type metric detected
        - record: job:{{$metric}}:rate5m
          expr:  sum(rate({{$metric}}[5m])) without (instance, pod)
        - record: job:{{$metric}}:rate10m
          expr:  sum(rate({{$metric}}[10m])) without (instance, pod)
        - record: job:{{$metric}}:rate15m
          expr:  sum(rate({{$metric}}[15m])) without (instance, pod)
        {{- else }}
        # Other type metric detected
        - record: job:{{$metric}}:sum
          expr: sum({{$metric}}) without (instance, pod)
        - record: job:{{$metric}}:min
          expr: min({{$metric}}) without (instance, pod)
        - record: job:{{$metric}}:max
          expr: max({{$metric}}) without (instance, pod)
        - record: job:{{$metric}}:avg
          expr: avg({{$metric}}) without (instance, pod)
        {{- end }}
        - record: job:{{$metric}}:count
          expr: count({{$metric}}) without (instance, pod)
        {{ end }}

    metrics_per_prometheus_rule: 500 # please re-adjust that for production setup
    k8s_prometheus_operator_enabled: true
    k8s_prometheus_rule: monitoring/app-metrics
kind: ConfigMap
```
