### DISCUSSION TITLE
eBPF 101 - curated writings on basics of ebpf

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#478] [Joy of Programming]
### Learn Through Links
```yaml
- https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere # supported kernels
```

### 101 - ELF - Map & Program
```yaml
- elf stands for executable & linkable format
- elf is a standard format for executable files, object code, core dumps, shared libraries

- **BPF ELF file**
- bpf map & program are defined in elf file
- bpf program uses a reference to this bpf map

- **BPF ELF loader**
- Creates the map defined in elf via a syscall & returns a fd
- Rewrites all the references to the map with this fd
- Loads the **patched bytecode** via bpf syscall & returns a fd

- **Attaching**
- Once loaded successfully, the bpf program can be attached to variety of kernel subsystems
- Some subsystems use a SIMPLE SYSCALL (e.g. SO_ATTACH)
- Others require netlink messages (XDP) 
- Or manipulating the tracefs (kprobes, tracepoints)

- https://kinvolk.io/blog/2018/10/exploring-bpf-elf-loaders-at-the-bpf-hackfest/#common-steps
```

### 101 - BPF Helpers
```yaml
- These functions are restricted to a white-list of helpers defined in the kernel
- These helpers are used by eBPF programs to interact with the system

- Since there are several eBPF program types, and that they do not run in the same context
- Each program type can only call a subset of those helpers

- Due to eBPF conventions, a helper can not have more than five arguments

- Internally, eBPF programs call directly into the compiled helper functions without FFI
- As a result, calling helpers introduces no overhead, thus offering excellent performance

- Tags / Key Words To Search:
  - ingress, egress, redirect, packet

- https://man7.org/linux/man-pages/man7/bpf-helpers.7.html
```

### 101 - Tips - Ring Buffer
```yaml
- Ring buffer is shared across all CPUs, meaning no per-CPU allocation
- Starting in Linux 5.8

- https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#5-bpf_ringbuf_output
```

### 101 - Incomplete Guide On How To In BCC
```yaml
- Notes:
  - All arguments to kernel function when probed are VARIADIC
```

```c
// Syntax: kprobe__kernel_function_name
int kprobe__tcp_v4_connect(struct pt_regs *ctx, struct sock *sk)
```
```c
// Syntax: kretprobe__kernel_function_name
int kretprobe__tcp_v4_connect(struct pt_regs *ctx)
```

```c
// Syntax: TRACEPOINT_PROBE(category, event)
// This is a Macro
// Arguments are available in an args struct, which are the tracepoint arguments
// One way to list these is to cat the relevant format file under /sys/kernel/debug/tracing/events/category/event/format
TRACEPOINT_PROBE(random, urandom_read) // an example
```

```c
// Syntax: RAW_TRACEPOINT_PROBE(event)
// This is a macro that instruments the raw tracepoint defined by event

// The argument is a pointer to struct bpf_raw_tracepoint_args, which is defined in bpf.h
// https://github.com/iovisor/bcc/blob/master/src/cc/compat/linux/virtual_bpf.h

// The struct field args contains all parameters of the raw tracepoint where you can found at linux tree 
// https://github.com/torvalds/linux/tree/master/include/trace/events directory

RAW_TRACEPOINT_PROBE(sched_switch)
```

```yaml
- https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#bpf-c
```

### 201 - How To Tracepoints
```yaml
- Common ways to insert ebpf 
- Via **kprobe/kretprobe** and **tracepoint**

- kprobe is flexible but FRAGILE
- Kernel can change function signature including args

- tracepoints are pre-defined kernel hooks 
- Represent events of interest 
- Hence STABLE API

- ebpf programs may store intermediate data in kernel-space eBPF maps 
- NOTE: maps are in kernel

- **BPF_MAP_TYPE_PERF_EVENT_ARRAY** is used to deliver events to user space
 
- Tracepoints to track processes
- **task/task_newtask**
- **sched/sched_process_exit**

- **Arguments format** of a particular tracepoint can be found in the corresponding file in **sysfs**
- cat /sys/kernel/debug/tracing/events/task/task_newtask/format

- bpf_map_update_elem(..) for map BPF_MAP_TYPE_HASH
- bpf_perf_event_output(..) for map BPF_MAP_TYPE_PERF_EVENT_ARRAY
- bpf_map_lookup_elem(...) for map BPF_MAP_TYPE_PERF_EVENT_ARRAY

- SEC("tracepoint/task/task_newtask")
- SEC("tracepoint/oom/mark_victim")
- SEC("tracepoint/sched/sched_process_exit")

- BPF CO-RE
- https://coroot.com/blog/ebpf-portability
```

### 201 - How To Trace HTTP
```yaml
- kprobe provides a mechanism to trace the Kernel API or internals
- uprobe provides a mechanism to intercept specific instructions in a user program

- If we capture the Kernel interface:
  - We should be able to capture all the ingress and egress data and reconstruct the HTTP requests

- Alternatively, we can use uprobes to carefully instrument underlying HTTP libraries (eg. net/http in Go):
  - To capture HTTP requests directly
  - Since uprobes work at the application level, their implementation will be dependent on the underlying language used

- kprobes work across the entire system
- So we need to filter by PID to limit capturing the data to only the processes of interest

- One downside to capturing data using kprobes is:
  - We need to reparse all responses since we intercept them after they have been converted to the write format
- An alternative approach is to use uprobes to capture the data before it gets sent to the kernel:
  - Where we can read the data before it has been serialized

- kprobes do not work with TLS

- https://blog.px.dev/ebpf-http-tracing/
- https://github.com/pixie-io/pixie-demos/tree/main/simple-gotracing
```

### 401 - Library coroot - Containers & Network
```yaml
- Monitor all TCP connections on a node
- Associate them to related container
- Exports metrics to Prometheus

- Total number of successful TCP connects i.e. counter
- Number of active outbound connections used by the container i.e. gauge
- Total number of failed TCP connects i.e. counter
- Listen address of the container i.e. gauge

- Above metrics are obtained using the **sock:inet_sock_set_state** kernel tracepoint
- As the name implies, this tracepoint is called whenever a TCP connection changes its state
 
- Initialization Logic
- How will agent detect all connections that were established before it started
- It reads the info about established connections from:
  - **/proc/net/tcp** &
  - **/proc/net/tcp6** in each network namespace on startup
- The inode of each connection from these files is mapped with **/proc/<pid>/fd** to find the **corresponding container**
 
- WOW 
- ebpf can provide a bird's view of distributed architecture sans proxy based service mesh

- https://coroot.com/blog/building-a-service-map-using-ebpf
- https://www.kernel.org/doc/Documentation/networking/timestamping.txt # system time # may not be monotonic
```
