### DISCUSSION TITLE
golang: perf: AppendFormat vs Format

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#487] [Joy of Programming]
```yaml
- AppendFormat vs Format:

- AppendFormat
- Reduce allocations & hence increase efficiency
- Allows the same operation to use a fixed-size allocation & hence stack
- Hence, AppendFormat passes the compiler’s stack allocation checks

- Format contains allocations of SIZES that can NOT be DETERMINED at COMPILE time 
- Hence do not qualify for stack

- Notes on passing PREALLOCATED buffers:
  - String is a READ-ONLY slice of bytes 
  - Fixed sized array are known at compile time & hence are stack allocated
  - Convert the fixed-size array 'a' to a slice type represented by 'b'
  - 'b' is backed by the array 'a'

- https://github.com/go-sql-driver/mysql/pull/615/files
- https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/time/format.go;l=587-599
```
