### DISCUSSION TITLE
computer represents an integer as two's complement

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#498] [Joy of Programming]
```
https://www.cs.cornell.edu/~tomf/notes/cps104/twoscomp.html
```
```yaml
- Whats two's complement then?
```
```yaml
- q: represent a negative number i.e. -28 in two's complement
- step 1: represent the integer in its binary form
- step 2: invert all the digits i.e. 0 becomes 1 & 1 becomes 0
- step 3: add 1 to the binary form
- quirk: why negative number is thought of first?
```
```yaml
- known: a leading 0 means positive number
- known: a leading 1 means negative number 
```
```yaml
- 0xFFFFFFFF
- **step 1**: 1111 1111 1111 1111 1111 1111 1111 1111 in binary
- known: leading 1 means negative number
- query: negative of what number?
- tip: do it the computer's way
- **step 2**: invert the bits from the resulting binary form
- **step 3**: add 1 to the inverted bits
- ans: -1 i.e. computer's 0xFFFFFFFF is -1 for humans
- quirk: why negative though? why are we only experimenting with negative numbers?
```
```yaml
- given: -30
- quirk: why negative number?
- step 1: convert to binary
- step 2: invert the binary bits
- step 3: add 1
- result: convert to hexadecimal if you need result in hex
- quirk: why thinking in negative, binary & hexadecimal?
```
```yaml
- til: with two's complement the addition & subtraction is unified
- til: quirk: we add always even if its a subtraction
```
```yaml
- given: 100 - 10
- hint: compute using computer's way
- step 1: 100 + (-10)
- step 2: represent 10 in binary form
- step 3: invert binary form of 10
- step 4: add 1 to above inverted bits
- step 5: add above result with binary form of 100
```
```yaml
- quirk: why inverting and add one works?
- quirk: why invert and add one makes sense mathematically?
- hint: read the reference
```
