### DISCUSSION TITLE
golang: creating lots of short-lived objects vs. object pooling

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#504] [Joy of Programming]
### Why
```yaml
- Creating lots of short-lived objects which will cause the GC to thrash
- Object pooling can help here
```

### Experiment
```yaml
- Compare allocating structs in 10 concurrent goroutines on the heap vs. using a sync.Pool for the same purpose
```

### Understand
```yaml
- til: It’s important to point out that Go’s sync.Pool is drained during garbage collection
- til: The purpose of sync.Pool is to **reuse memory** between garbage collections
- http://dominik.honnef.co/go-tip/2014-01-10/#syncpool

- One can maintain their OWN FREE LIST of OBJECTs to hold onto memory across garbage collection cycles
- Though this arguably subverts the purpose of a garbage collector

- Go’s pprof tool is extremely useful for profiling memory usage
- Use it before blindly making memory optimizations
```
