### DISCUSSION TITLE
golang: generate: perf: one string & use of arrays only

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#506] [Joy of Programming]
```
https://go.dev/blog/generate
```

### Important Performance Discussions
```yaml
- All the names are smashed together into a single string, which saves memory:
  - Only one string header for all the names, even if there are zillions of them
- Then an array, _Pill_index, maps from value to name by a simple, efficient technique
- Note too that _Pill_index is an array (not a slice; one more header eliminated) 
- _Pill_index is an array of uint8 which is the smallest integer sufficient to span the space of values
```

```yaml
- There are lots of other uses of go generate already installed in the Go tree
- Examples include:
  - Generating Unicode tables in the unicode package:
    - Creating efficient methods for encoding and decoding arrays in encoding/gob
  - Producing time zone data in the time package, and so on
```
