### DISCUSSION TITLE
curated design thinking

### DISCUSSION THREAD

**Discussion by AmitKumarDas** [AmitKumarDas/fun-with-programming#511] [Joy of Programming]
```yaml
- When: Versions were bumped based on the recommendation from xyz
- Then: Ensure that any bumps due to CVE fixes or critical bugs are not reverted incase upstream not yet taken care of it
- Then: Should return to version alignment with upstream components in next couple of revs
- And: Divergence from upstream versions need to be by exception and clearly described
- And: New capability for tests to enable path to a default “latest patches” policy update
```

```yaml
- 2 years General Support with an additional 9 month of Extended Support
- One LTS Release per year (preferably not the first drop/minor release in a major release cycle)
- Able to upgrade directly from one LTS Release to the next LTS release
```

```yaml
- gRPC libraries share a maximalist design ethos that has led to extraordinary complexity
- We've found Connect a joy in production: it's small, simple, and debuggable
```

```yaml
- One way is to make it so simple that there are obviouSLY no deficiencies 
- and the other way is to make it so complicated that there are no OBVious deficiencies __ Tony Hoare 
```

```yaml
- As well as being very simple to use, a software program must be very DIFFicult to MISuse; 
- it must be kind to programming errors, giving clear indication of their occurrence, 
- and NEVer becoming unPREDictable in its effects __ Tony Hoare 
```
