### ISSUE TITLE
[mon] sticky notes

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/fun-with-programming#42]
### Prometheus Blackbox Exporter
```
https://www.robustperception.io/checking-for-http-200s-with-the-blackbox-exporter
```
```
- http://localhost:9115/probe?module=http_2xx&target=https://www.robustperception.io/
- you will see the result of a probe of https://www.robustperception.io/
- probe_success metric will be 1 if the probe succeeded
- and 0 if it failed
```
```yaml
# Sample Prometheus config
global:
 scrape_interval: 10s
scrape_configs:
 - job_name: blackbox
   metrics_path: /probe
   params:
    module: [http_2xx]
   static_configs:
   - targets:
    - https://www.robustperception.io/probe
    - http://prometheus.io/blog
   relabel_configs:
   - source_labels: [__address__]
     target_label: __param_target
   - source_labels: [__param_target]
     target_label: instance
     # The relabel_configs change the usual targets
     # into URL parameters on the blackbox exporter
   - target_label: __address__
     replacement: 127.0.0.1:9115 # The blackbox exporter
```
```yaml
# alert
groups:
- name: example
  rules:
   - alert: ProbeFailing
     expr: up{job="blackbox"} == 0 or probe_success{job="blackbox"} == 0
     for: 10m
```

**Comment by AmitKumarDas** [comment]
```go
// https://sysdig.com/blog/debug-kubernetes-crashloopbackoff/
//
// Kubernetes Events
kubernetes:
    node:
      - TerminatedAllPods       # Terminated All Pods      (information)
      - RegisteredNode          # Node Registered          (information)*
      - RemovingNode            # Removing Node            (information)*
      - DeletingNode            # Deleting Node            (information)*
      - DeletingAllPods         # Deleting All Pods        (information)
      - TerminatingEvictedPod   # Terminating Evicted Pod  (information)*
      - NodeReady               # Node Ready               (information)*
      - NodeNotReady            # Node not Ready           (information)*
      - NodeSchedulable         # Node is Schedulable      (information)*
      - NodeNotSchedulable      # Node is not Schedulable  (information)*
      - CIDRNotAvailable        # CIDR not Available       (information)*
      - CIDRAssignmentFailed    # CIDR Assignment Failed   (information)*
      - Starting                # Starting Kubelet         (information)*
      - KubeletSetupFailed      # Kubelet Setup Failed     (warning)*
      - FailedMount             # Volume Mount Failed      (warning)*
      - NodeSelectorMismatching # Node Selector Mismatch   (warning)*
      - InsufficientFreeCPU     # Insufficient Free CPU    (warning)*
      - InsufficientFreeMemory  # Insufficient Free Mem    (warning)*
      - OutOfDisk               # Out of Disk              (information)*
      - HostNetworkNotSupported # Host Ntw not Supported   (warning)*
      - NilShaper               # Undefined Shaper         (warning)*
      - Rebooted                # Node Rebooted            (warning)*
      - NodeHasSufficientDisk   # Node Has Sufficient Disk (information)*
      - NodeOutOfDisk           # Node Out of Disk Space   (information)*
      - InvalidDiskCapacity     # Invalid Disk Capacity    (warning)*
      - FreeDiskSpaceFailed     # Free Disk Space Failed   (warning)*
    pod:
      - Pulling           # Pulling Container Image          (information)
      - Pulled            # Ctr Img Pulled                   (information)
      - Failed            # Ctr Img Pull/Create/Start Fail   (warning)*
      - InspectFailed     # Ctr Img Inspect Failed           (warning)*
      - ErrImageNeverPull # Ctr Img NeverPull Policy Violate (warning)*
      - BackOff           # Back Off Ctr Start, Image Pull   (warning)
      - Created           # Container Created                (information)
      - Started           # Container Started                (information)
      - Killing           # Killing Container                (information)*
      - Unhealthy         # Container Unhealthy              (warning)
      - FailedSync        # Pod Sync Failed                  (warning)
      - FailedValidation  # Failed Pod Config Validation     (warning)
      - OutOfDisk         # Out of Disk                      (information)*
      - HostPortConflict  # Host/Port Conflict               (warning)*
    replicationController:
      - SuccessfulCreate    # Pod Created        (information)*
      - FailedCreate        # Pod Create Failed  (warning)*
      - SuccessfulDelete    # Pod Deleted        (information)*
      - FailedDelete        # Pod Delete Failed  (warning)*
```

**Comment by AmitKumarDas** [comment]
```py
# https://samirbehara.com/2018/07/09/crash-loop-detection-in-kubernetes/
def test_kubernetes_pod_status_is_running(k8s_client):

    podlist = k8s_client.list_namespaced_pod("default")

    # Iterate through all the pods in the default namespace and verify that they are Running
    for item in podlist.items:
 
        pod = k8s_client.read_namespaced_pod_status(namespace='default', name=item.metadata.name)
 
        print("%s\t%s\t" % (item.metadata.name, item.metadata.namespace))
        print(pod.status.phase)
        assert(pod.status.phase == "Running" )
```

**Comment by AmitKumarDas** [comment]
```go
// https://containersolutions.github.io/runbooks/posts/kubernetes/crashloopbackoff/
```

**Comment by AmitKumarDas** [comment]
```go
// https://kubernetes.io/docs/concepts/cluster-administration/logging/
```

**Comment by AmitKumarDas** [comment]
```yaml
# https://zerokspot.com/weblog/2019/11/25/testing-prometheus-alerts/
#
# e.g. if some app has been unreachable for more than 5 minutes, 
# I want to get notified. To achieve that I have added the following rule 
groups:
  - name: zerokspot
    rules:
      - alert: zerokspot--sys--down
        expr: up{job="zerokspot-sys"} == 0
        for: 5m
```
