### ISSUE TITLE
[k8s] sticky

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/fun-with-programming#48]
```go
// get the external URL
// check if Admin API is enabled
// check if AlertManager is configured to Prometheus
// check the retention period
// check the storage i.e. PV capacity
//
// kubectl get crd prometheuses.monitoring.coreos.com
// kubectl get prometheus --all-namespaces -oyaml
```

**Comment by AmitKumarDas** [comment]
```sh
kubectl get prometheusrules --all-namespaces

NAMESPACE    NAME                                                              AGE
monitoring   kube-prometheus-stack-cpu-mem-net-recording                       2d2h
monitoring   prometheus-stack-kube-prom-alertmanager.rules                     2d2h
monitoring   prometheus-stack-kube-prom-etcd                                   2d2h
monitoring   prometheus-stack-kube-prom-general.rules                          2d2h
monitoring   prometheus-stack-kube-prom-k8s.rules                              2d2h
monitoring   prometheus-stack-kube-prom-kube-apiserver-availability.rules      2d2h
monitoring   prometheus-stack-kube-prom-kube-apiserver-slos                    2d2h
monitoring   prometheus-stack-kube-prom-kube-apiserver.rules                   2d2h
monitoring   prometheus-stack-kube-prom-kube-prometheus-general.rules          2d2h
monitoring   prometheus-stack-kube-prom-kube-prometheus-node-recording.rules   2d2h
monitoring   prometheus-stack-kube-prom-kube-state-metrics                     2d2h
monitoring   prometheus-stack-kube-prom-kubelet.rules                          2d2h
monitoring   prometheus-stack-kube-prom-kubernetes-apps                        2d2h
monitoring   prometheus-stack-kube-prom-kubernetes-resources                   2d2h
monitoring   prometheus-stack-kube-prom-kubernetes-storage                     2d2h
monitoring   prometheus-stack-kube-prom-kubernetes-system                      2d2h
monitoring   prometheus-stack-kube-prom-kubernetes-system-apiserver            2d2h
monitoring   prometheus-stack-kube-prom-kubernetes-system-kubelet              2d2h
monitoring   prometheus-stack-kube-prom-node-exporter                          2d2h
monitoring   prometheus-stack-kube-prom-node-exporter.rules                    2d2h
monitoring   prometheus-stack-kube-prom-node-network                           2d2h
monitoring   prometheus-stack-kube-prom-node.rules                             2d2h
monitoring   prometheus-stack-kube-prom-prometheus                             2d2h
monitoring   prometheus-stack-kube-prom-prometheus-operator                    2d2h
```

**Comment by AmitKumarDas** [comment]
```sh
kubectl get servicemonitors --all-namespaces

NAMESPACE           NAME                                            AGE
monitoring          missing-container-metrics                       2d2h
monitoring          prometheus-stack-kube-prom-alertmanager         2d2h
monitoring          prometheus-stack-kube-prom-apiserver            2d2h
monitoring          prometheus-stack-kube-prom-coredns              2d2h
monitoring          prometheus-stack-kube-prom-grafana              2d2h
monitoring          prometheus-stack-kube-prom-kube-etcd            2d2h
monitoring          prometheus-stack-kube-prom-kube-state-metrics   2d2h
monitoring          prometheus-stack-kube-prom-kubelet              2d2h
monitoring          prometheus-stack-kube-prom-node-exporter        2d2h
monitoring          prometheus-stack-kube-prom-operator             2d2h
monitoring          prometheus-stack-kube-prom-prometheus           2d2h
wonderland-system   wonderland-controller-manager-metrics-monitor   2d2h
```

**Comment by AmitKumarDas** [comment]
```go
type KubeConfig struct {
	Clusters []struct {
		Name    string `json:"name"`
		Cluster struct {
			Server                   string `json:"server"`
			CertificateAuthorityData string `json:"certificate-authority-data"`
			ProxyURL                 string `json:"proxy-url"`
		} `json:"cluster"`
	} `json:"clusters"`
	Users []struct {
		Name string `json:"name"`
		User struct {
			Token string `json:"token"`
		} `json:"user"`
	} `json:"users"`
	Contexts []struct {
		Name    string `json:"name"`
		Context struct {
			Cluster string `json:"cluster"`
			User    string `json:"user"`
		} `json:"context"`
	} `json:"contexts"`
	CurrentContext string `json:"current-context"`
}
```

**Comment by AmitKumarDas** [comment]
```sh
# default alertmanager config that has route & receiver configuration
kubectl -n monitoring exec alertmanager-prometheus-stack-kube-prom-alertmanager-0 -it sh
cat /etc/alertmanager/config/alertmanager.yaml
```

**Comment by AmitKumarDas** [comment]
```yaml
# kubectl -n monitoring get prometheusrules prometheus-stack-kube-prom-kube-apiserver-slos  -oyaml

spec:
  groups:
  - name: kube-apiserver-slos
    rules:
    - alert: KubeAPIErrorBudgetBurn
      annotations:
        description: The API server is burning too much error budget.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
        summary: The API server is burning too much error budget.
      expr: |-
        sum(apiserver_request:burnrate1h) > (14.40 * 0.01000)
        and
        sum(apiserver_request:burnrate5m) > (14.40 * 0.01000)
      for: 2m
      labels:
        long: 1h
        severity: critical
        short: 5m
    - alert: KubeAPIErrorBudgetBurn
      annotations:
        description: The API server is burning too much error budget.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
        summary: The API server is burning too much error budget.
      expr: |-
        sum(apiserver_request:burnrate6h) > (6.00 * 0.01000)
        and
        sum(apiserver_request:burnrate30m) > (6.00 * 0.01000)
      for: 15m
      labels:
        long: 6h
        severity: critical
        short: 30m
    - alert: KubeAPIErrorBudgetBurn
      annotations:
        description: The API server is burning too much error budget.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
        summary: The API server is burning too much error budget.
      expr: |-
        sum(apiserver_request:burnrate1d) > (3.00 * 0.01000)
        and
        sum(apiserver_request:burnrate2h) > (3.00 * 0.01000)
      for: 1h
      labels:
        long: 1d
        severity: warning
        short: 2h
    - alert: KubeAPIErrorBudgetBurn
      annotations:
        description: The API server is burning too much error budget.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapierrorbudgetburn
        summary: The API server is burning too much error budget.
      expr: |-
        sum(apiserver_request:burnrate3d) > (1.00 * 0.01000)
        and
        sum(apiserver_request:burnrate6h) > (1.00 * 0.01000)
      for: 3h
      labels:
        long: 3d
        severity: warning
        short: 6h
```
