### ISSUE TITLE
0004

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/fun-with-programming#82]
```go
// tags: aws, network, eni, cni
//
// https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md
// https://github.com/aws/amazon-vpc-cni-k8s
```

**Comment by AmitKumarDas** [comment]
```go
// tags: anti patterns, k8s, deployment, terraform, kubectl, helm, workstation
//
// https://codefresh.io/kubernetes-tutorial/kubernetes-antipatterns-1/
```

**Comment by AmitKumarDas** [comment]
```go
// tags: troubleshooting, runbook, dns, 5xx errors, coredns
//
// https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
// https://www.infracloud.io/blogs/using-coredns-effectively-kubernetes/
```

**Comment by AmitKumarDas** [comment]
```go
// tags: kubelet garbage collection for container images
//
// https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
```

**Comment by AmitKumarDas** [comment]
```go
// til: kube-proxy, istio, firewall, user space, kernel, cni, 
//
// https://www.stackrox.com/post/2020/01/kubernetes-networking-demystified/
```

**Comment by AmitKumarDas** [comment]
```sh
# tags: monitor kube-proxy
#
$ curl https://[kube_proxy_ip]:10249/metrics
...
# HELP rest_client_request_duration_seconds Request latency in seconds. Broken down by verb and URL.
# TYPE rest_client_request_duration_seconds histogram
rest_client_request_duration_seconds_bucket{url="/https://XXXX%7Bprefix%7D",verb="GET",le="0.001"} 41
rest_client_request_duration_seconds_bucket{url="https://XXXX/%7Bprefix%7D",verb="GET",le="0.002"} 88
rest_client_request_duration_seconds_bucket{url="https://XXXX/%7Bprefix%7D",verb="GET",le="0.004"} 89
rest_client_request_duration_seconds_count{url="https://XXXX/%7Bprefix%7D",verb="POST"} 7
# HELP rest_client_request_latency_seconds (Deprecated) Request latency in seconds. Broken down by verb and URL.
# TYPE rest_client_request_latency_seconds histogram
rest_client_request_latency_seconds_bucket{url="https://XXXX/%7Bprefix%7D",verb="GET",le="0.001"} 41
...
rest_client_request_latency_seconds_sum{url="https://XXXX/%7Bprefix%7D",verb="POST"} 0.0122645
rest_client_request_latency_seconds_count{url="https://XXXX/%7Bprefix%7D",verb="POST"} 7
# HELP rest_client_requests_total Number of HTTP requests, partitioned by status code, method, and host.
# TYPE rest_client_requests_total counter
rest_client_requests_total{code="200",host="XXXX",method="GET"} 26495
rest_client_requests_total{code="201",host="XXXX",method="POST"} 1
rest_client_requests_total{code="<error>",host="XXXX",method="GET"} 91
...
```
```go
// https://sysdig.com/blog/monitor-kube-proxy/
```
```yaml
# If you want to configure a Prometheus server to scrape kube-proxy, 
# just add the next job to your scrape configuration:
# Remember to customize it with your own labels and relabeling configuration as needed
- job_name: kube-proxy
 honor_labels: true
 kubernetes_sd_configs:
 - role: pod
 relabel_configs:
 - action: keep
   source_labels:
   - __meta_kubernetes_namespace
   - __meta_kubernetes_pod_name
   separator: '/'
   regex: 'kube-system/kube-proxy.+'
 - source_labels:
   - __address__
   action: replace
   target_label: __address__
   regex: (.+?)(\\:\\d+)?
   replacement: $1:10249
```
